# general settings
title: BAMF
subtitle: General Contracting
email: bamfgeneralcontracting@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  BAMF General Contracting
baseurl: ""
url: "https://bamfgc.com"
twitter:
  username: ""
facebook:
  username: "BAMFGeneralContracting"
contact_info:
  address: 1278 Normandie Court, Avon IN 46123
  phone: 317.281.2559

# directory settings
source: src
destination: build

# style settings
sass:
  sass_dir: assets/_sass
  style: compressed

# collections
collections:
  - services

width: 500

# Build settings
markdown: kramdown
gems:
  - jekyll-autoprefixer
  - jekyll-maps # https://github.com/ayastreb/jekyll-maps
  - jekyll-minifier
  - jekyll-seo-tag # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-sitemap # https://github.com/jekyll/jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - node_modules
  - .rubocop_todo.yml
