---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections:
- path: src
  label: Pages
  create: all
- path: src/_posts
  label: Posts
  create: all
- path: src/_reviews
  label: Reviews
  create: all
- path: src/_services
  label: Services
  create: all
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
