---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
collections:
- path: _services
  label: Services
  create: all
- path: _posts
  label: Posts
  create: all
upload_dir: src/assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
